format: yamanifest
version: 1.0
---
csiro_bgc.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/csiro_bgc.res.nc-01001231
  hashes:
    binhash: 928210b4949476e54d04e08f3462cba0
    md5: 36eddc51730941934ad070439525719f
csiro_bgc_sediment.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/csiro_bgc_sediment.res.nc-01001231
  hashes:
    binhash: 87d4ba06bcd55dd60fc841f2eecd96f5
    md5: c19814b8cd24d34c1d0f6ede4b94426c
ocean_age.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_age.res.nc-01001231
  hashes:
    binhash: 1e3ba44dedaefef5367d23eac1be5a40
    md5: 5ad601c0eaad3cfc3baa47aed91d1af9
ocean_barotropic.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_barotropic.res.nc-01001231
  hashes:
    binhash: 542dcc852c58bfbdb11e24d64d95cee3
    md5: 97a5f4dc4a379ea4cad9f5d342ed6c51
ocean_bih_friction.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_bih_friction.res.nc-01001231
  hashes:
    binhash: a426565293270cd2462ed2cdad99f578
    md5: 78ebb71bbf0e28e14d72243cf48a483c
ocean_density.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_density.res.nc-01001231
  hashes:
    binhash: 4260aa4bd911e556a70bcb647bca1fd3
    md5: 2ea72f188feac5017d4c7456f514e1e6
ocean_frazil.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_frazil.res.nc-01001231
  hashes:
    binhash: a147b08214b0455f3c2800ea11a8a66d
    md5: dfd57082dc58081e9ed6b515f2d8a4c1
ocean_lap_friction.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_lap_friction.res.nc-01001231
  hashes:
    binhash: 8b79f4303773f488dda707f553da81a8
    md5: 2c1dbc74450e72925f9dbe7486689675
ocean_neutral.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_neutral.res.nc-01001231
  hashes:
    binhash: b3fec4ad12347677f30d4018801d0d92
    md5: fab54ae81945add9ae5e850a4569ec34
ocean_pot_temp.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_pot_temp.res.nc-01001231
  hashes:
    binhash: 5a3c1fde21c74f43dc49bd2c698d2daf
    md5: dd179d49d13b0b11d524df725b6eec05
ocean_sbc.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_sbc.res.nc-01001231
  hashes:
    binhash: ebe0aa5c179eb6338b5ae01e0ff2f8d9
    md5: 655ee14d694588f2cdb870535df0b042
ocean_sigma_transport.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_sigma_transport.res.nc-01001231
  hashes:
    binhash: b48ff814f83971448582e87949ec0942
    md5: fe527a9917d30955d0dc082271c1392f
ocean_solo.res-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_solo.res-01001231
  hashes:
    binhash: ec55bd0b47af8eebb336209a97374bd8
    md5: 354221e55782d6c1ffff3f9c3df24ffd
ocean_temp_salt.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_temp_salt.res.nc-01001231
  hashes:
    binhash: e6b495d0e4069924232b98de2a7aec31
    md5: cd1b95ef3ac60f9e1f5af29d6bb2d4d5
ocean_thickness.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_thickness.res.nc-01001231
  hashes:
    binhash: 3028db01d30344e471073d3890342a66
    md5: 5a9bbbca1e6fd2c963db84dda5a84acf
ocean_tracer.res-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_tracer.res-01001231
  hashes:
    binhash: 8d45c50d4bcf443522a542f53688fe08
    md5: 5e5db59b3963b8130ccc76557ed2badc
ocean_velocity.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_velocity.res.nc-01001231
  hashes:
    binhash: bdf81d0ca54d8864be40a48abe551395
    md5: 287edec7690400b797b1cbf6e1ea60f0
ocean_velocity_advection.res.nc-01001231:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/pre-industrial/restart/ocean/ocean_velocity_advection.res.nc-01001231
  hashes:
    binhash: 2c53fe3165c904bde1fbdf2723dae5cc
    md5: 653ffae21c9f0a18718d441d591798a1
