format: yamanifest
version: 1.0
---
.manifest.yaml:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2026.02.10/.manifest.yaml
  hashes:
    binhash: 57bbb6b00a37f824159ffd776794b428
    md5: 2a1fac55171be20a365bd7a961c57135
pftlookup_cable3_Pfix.csv:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/share/atmosphere/land/biogeochemistry/resolution_independent/2026.02.10/pftlookup_cable3_Pfix.csv
  hashes:
    binhash: fe0c4ad208586a2ccf2cb113919a8332
    md5: d9a4d71ee8038029739c23a1b829ab6a
