format: yamanifest
version: 1.0
---
a2i.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.06.11/coupler/a2i.nc
  hashes:
    binhash: 8f867d131f2440fe66ac63942cf2b0d1
    md5: 5e401792d7bda7cbfbfeadcd20ea8f89
i2a.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.06.11/coupler/i2a.nc
  hashes:
    binhash: 8198472a1ffc043ffa821422e7695258
    md5: d88313e65d31d532a70c4f9e12d356a7
o2i.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.06.11/coupler/o2i.nc
  hashes:
    binhash: bfbb4ea65b61be57616b340468c5ba01
    md5: b9e2d2f707e5216b6fbb5c680075a049
