format: yamanifest
version: 1.0
---
ocean_age.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_age.res.nc
  hashes:
    binhash: 172d6add061c6049d057533b493fa273
    md5: de6e89f46f6443b9f0d78ea705b851c0
ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 3c1551a71721cc067ef07a9f380360a8
    md5: f7f169fc9eaba70fb33da108bb4a59e6
ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f01bbfb3d78a3ae5409592835bd0bbb0
    md5: ed2ece7f976333a6a61fc0162dee67e9
ocean_density.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_density.res.nc
  hashes:
    binhash: a63a5a10beda90c39a6eb2584e89ca16
    md5: 4c1b793cefbedd8df1a1967492f1686b
ocean_frazil.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 9dddd8f0b5d8acb51903a03002b464ab
    md5: 9c0641dafd9ea99f9fcb983ba3f5f759
ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 01d12af05a5a642c2775b34ad5821935
    md5: 6deb5c56e692bc94fdc80fe8cc106345
ocean_neutral.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 09458c77f832314c290935859e566219
    md5: 2537660424bb7e82bc7aa1d09baad7b0
ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 15c6c48185fe92029ee0678a6b4d463e
    md5: 74c3473ec23d0ba5dca019f9b946b8d0
ocean_sbc.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 6b9c4acd6c3ec499a22613d090404eff
    md5: 8d2b07d193deeb1702f88f5c3704c8d3
ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 74f7183a43f905886434527819601029
    md5: 13cedb1ccde6b993fbd12afc326975f1
ocean_solo.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_solo.res
  hashes:
    binhash: 9bb8803cfb9d43562d6d4c7a39495cd1
    md5: 253e7f183a6043e3e4410fd000dfcb8a
ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 7f21d9f480dd8c8634b8bb1db39c8cb4
    md5: bdf1ed198f9e540a4987b4c0533d92af
ocean_thickness.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 9e8fff92b2c2ef0e87cb99b3442b02ee
    md5: ebbc47480fa38bf256edc3bfeac31f06
ocean_tracer.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_tracer.res
  hashes:
    binhash: 100c4a0bc5808ae21183001dca01eda5
    md5: 75bc4ddae27d69c16d5de7a5deb9598b
ocean_velocity.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 642b712e91cede07288eba496dcdac6c
    md5: be0274fd35d74f9ac8a37d617dd4743a
ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 55c14560d85ee66351566937299267d6
    md5: 91f9a2fedba6acc65a0c4381ac4edaa6
ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 1362207ba5c5b4b77719ddbaa9c48519
    md5: 4e2274ff329bdc3ead6d991fba876a00
ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/scen7-vl/restart/2026.08.04/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 5481840c276f73e1bfbbe7b30a5190f7
    md5: 82eb4684dea12e353c4d99a6f9ebe2be
