format: yamanifest
version: 1.0
---
ocean_age.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_age.res.nc
  hashes:
    binhash: 94529c633a153aec2b3018a5b1ab832b
    md5: 773b4547f849cfc9ae1b8799ba60df40
ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 7dfb9662bbb56825134e5d96bbbfdd68
    md5: b671ca12ed16ec2432501ed15a27baeb
ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 82c1cdc9fc0dd64e8e3ca73735203c16
    md5: 2c26b57a28285a457c9bff4e07ef164d
ocean_density.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_density.res.nc
  hashes:
    binhash: 7efb8c65a2d646b0dbb15db3f4da26a8
    md5: 97e29be05c6f41805524ab98e8a1322a
ocean_frazil.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 5c9f02a5b1335507948775692e233242
    md5: 254815c9ce748f6a6faf101e2c1595ab
ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 3a8626fec38ef47c0a6f35307296ff3d
    md5: b4dbe36b824632d283704ba898edfd45
ocean_neutral.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7e36a88d6be2b9fc65d5950ffeeefdd8
    md5: 52274f095853d76cc4ef72589a96e7c0
ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 29e92ffdc41db510f504b194904b676c
    md5: af3609a6f7a77a282c988a390aa42b07
ocean_sbc.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_sbc.res.nc
  hashes:
    binhash: ff785eda68a05cb044b0543dee2fd073
    md5: b5235f808d0f3f7e6c1c8c56cd3762bb
ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 7719817eedcb42544e0b306841bf1bcc
    md5: 13cedb1ccde6b993fbd12afc326975f1
ocean_solo.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_solo.res
  hashes:
    binhash: 54ed00e220a2ba5ee8dc4ad90ca457b5
    md5: 934c67949b5bad56b7bb7caaed15ab67
ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: a07ed0fd7667ddbe74ff520988f59841
    md5: 086d13da40c41a4fa27f7835b5128d27
ocean_thickness.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 6bf4c047c0acd98552d1daef45e551ad
    md5: d125c8778b99714a573d27e09b0727f5
ocean_tracer.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_tracer.res
  hashes:
    binhash: 8336cbacd2b26eba0a918d92e84f300e
    md5: 19a9dabf34b0907ca8335f95e5c8728d
ocean_velocity.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_velocity.res.nc
  hashes:
    binhash: c63601394c706bd281f907d34cdde34e
    md5: 02c6d57686271c194a6d376c78a7eed3
ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a7c76ce9b7f53e88dfaf1937a1ea6098
    md5: e9079c9340cd380f7564dfa92389e3cb
ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 281e738aa5649fbe912a8035ed6256ee
    md5: b29d990c8c23c92b7381e412008e4fc0
ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical-emissions/restart/2026.05.27/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 58abd095e9a88c88d7b6ff6a68a139ab
    md5: 44109a04152c3437ea457fc3933ab52b
