format: yamanifest
version: 1.0
---
CO2_fluxes_h_2022_2100_cmip7.anc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/esm-scen7-h/atmosphere/forcing/global.N96/2026.08.14/CO2_fluxes_h_2022_2100_cmip7.anc
  hashes:
    binhash: f0348f0581f6933a83ecf4501340f876
    md5: 5af0fe14771e643afe52899fab00e169
README.md:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/esm-scen7-h/atmosphere/forcing/global.N96/2026.08.14/README.md
  hashes:
    binhash: 00dc85efaed51d72dba8debc07be2112
    md5: 7751db6d0efe0a2f2a79efd89481a7cb
