format: yamanifest
version: 1.0
---
i2o.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om2/ice/initial_conditions/global.025deg/2020.05.30/i2o.nc
  hashes:
    binhash: f8d2608e0cd012b77c24c0509aeb9c5d
    md5: ca16c9eef58814b9ff13fd5e8bd88a25
monthly_sstsss.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om2/ice/initial_conditions/global.025deg/2020.05.30/monthly_sstsss.nc
  hashes:
    binhash: 5cfa1bc2e1d4941c17d4cfe3dd369624
    md5: 598c7aa8a08fe3f48a621f781dd26331
o2i.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om2/ice/initial_conditions/global.025deg/2020.05.30/o2i.nc
  hashes:
    binhash: 8e4f5560ec1b1c9be46a134e6a3eaddd
    md5: 85c05d4bb45805be6346f2051f682028
u_star.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om2/ice/initial_conditions/global.025deg/2020.05.30/u_star.nc
  hashes:
    binhash: 7fb140bafdaf5e4f7d4a6a164a16fe76
    md5: 4be7800aa8e310a6c7a9c3af1d50c7f0
