format: yamanifest
version: 1.0
---
rmp_cice_to_um1t_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_cice_to_um1t_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 25469d1a591bac4a823fab31c4a525a3
    md5: f15237ecf7a9d3c2184bdc6766e21c19
rmp_cice_to_um1u_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_cice_to_um1u_CONSERV_FRACNNEI.nc
  hashes:
    binhash: bb85edae540c9a2df03c97471c1a70d1
    md5: 1af0789dbe4e5bf428b6c80be05a1481
rmp_cice_to_um1v_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_cice_to_um1v_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 05cff6bfbe5db1be1ccfaa664bfd702f
    md5: f30788fa9f38e8df6cd6fb36d76d5274
rmp_um1t_to_cice_CONSERV_DESTAREA.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1t_to_cice_CONSERV_DESTAREA.nc
  hashes:
    binhash: 8fb49cd703a5d4322ae376c156d81c17
    md5: b21b2648851b6669f8fec71288953647
rmp_um1t_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1t_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: f57e2b1bb8365c3b66f4e9dff7c519e1
    md5: 29ad892acb5516ffd501d0ef1c7f0716
rmp_um1u_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1u_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: 76dd8a2632f9f24c9c008ed56a9120f6
    md5: ddaa893e0485c65f8e72f60cb4ccb105
rmp_um1v_to_cice_CONSERV_FRACNNEI.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/share/coupler/remapping_weights/global.oi_1deg.a_N96/2025.08.06/rmp_um1v_to_cice_CONSERV_FRACNNEI.nc
  hashes:
    binhash: df320c62a9f91bc48c09172eb56c03d8
    md5: 2a5817b8136e8820fbdd4ed28cfb4098
