format: yamanifest
version: 1.0
---
CpoolLabile:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolLabile
  hashes:
    binhash: 7db409935173a1f1840de8ff9fbdf8f5
    md5: 91505bcf5eec1f0f18f1474d236685bb
CpoolLeaf:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolLeaf
  hashes:
    binhash: ba75b45ef13a06c5041be0c4453d32b4
    md5: 4ef11009f7fbc94c4bc0e857668487bb
CpoolLitterCwd:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolLitterCwd
  hashes:
    binhash: f7c0e253467edd8a2d52de935e324de5
    md5: 6bc837fc40af9cb2d1a9bb4ce2b33a00
CpoolLitterMtb:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolLitterMtb
  hashes:
    binhash: 08bfd8b3ebafb053d46144f597f4fa52
    md5: 6a13e432c0fbd7555a0b0589eedbeaea
CpoolLitterStr:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolLitterStr
  hashes:
    binhash: e6007d8949f3b6d1ecb75c0b75ca6d9f
    md5: 911f6c0b6edbc1becb61edc8b8877c5e
CpoolRoot:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolRoot
  hashes:
    binhash: dffe1925d5355c5d7e5df9b9962fd972
    md5: 9b6f3168650d7c7c7eb18dd8596c0e2f
CpoolSoilMic:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolSoilMic
  hashes:
    binhash: 32452b5772f371ae65fd75c352cf6fc8
    md5: ef5c8b02ab45146017a0b1b5c11e7fff
CpoolSoilPass:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolSoilPass
  hashes:
    binhash: 2cfd7505e1a1a674f773cddb895b11ba
    md5: 0d753b7e5532df9c909df7ec65c30ccd
CpoolSoilSlow:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolSoilSlow
  hashes:
    binhash: 5a22ebe4aef137cfd472d3a0561c46c0
    md5: 4aab006870270cf9614e52ba55be0feb
CpoolWood:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/CpoolWood
  hashes:
    binhash: 33b226b7f090a294d1fdaf510fcb0af3
    md5: 63110f15d6ad57d6e84bbdec8eee3ffd
Ndeposition:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/Ndeposition
  hashes:
    binhash: 51bb908b6179d54460cba892a0aa523e
    md5: babc53eeffdd7f290afb2672f5b8e1a3
Nfixation:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/Nfixation
  hashes:
    binhash: 29a2cafc8665a80f52af533aeca34cde
    md5: b72aad0d8c88f300c20fd9e25aed4e03
NpoolLeaf:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolLeaf
  hashes:
    binhash: 5fbec918f62d0a8b83211c92e6c85188
    md5: 4c6c5a16f9a2bd72643aaeaf2112c1c2
NpoolLitterCwd:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolLitterCwd
  hashes:
    binhash: 19a4abfdefbc206eb2b66d2fab592944
    md5: db2e1d88806e365c5037d5c866d84e0c
NpoolLitterMtb:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolLitterMtb
  hashes:
    binhash: 883780f84d79b50e64290d6b67e5e8c0
    md5: 4fc60d084cbe7c70c69e1690ea6ecde0
NpoolLitterStr:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolLitterStr
  hashes:
    binhash: 4416993fcf414432d8423d817255ac72
    md5: 3b3ad05b6ad5b1b7e1755516937f69e5
NpoolRoot:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolRoot
  hashes:
    binhash: b689a0bf8fa92b26d3e282dd7a5a339a
    md5: 5e54da63994883961383d5982aa3f843
NpoolSoilMic:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolSoilMic
  hashes:
    binhash: 04285beb9b66a1f657932179004195c8
    md5: ccc075551b75936250c68305ebbe5dd4
NpoolSoilMin:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolSoilMin
  hashes:
    binhash: 4694bada6deb8798895f36a8d498417e
    md5: 1bb7cf65612eb78174d3b4c9b570642a
NpoolSoilPass:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolSoilPass
  hashes:
    binhash: 1b2314b5b8bacc72bd832c6208c5c588
    md5: 3926125303c02c9bcbd959b0cbf89fa8
NpoolSoilSlow:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolSoilSlow
  hashes:
    binhash: e2e3523de881ba66d45d0a7ca3b1d9e5
    md5: f776dddafc7cf5d7415f63f3d700e759
NpoolWood:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/NpoolWood
  hashes:
    binhash: 920f5c9d28b629d6e68872f52c491961
    md5: 8b250df8ceb55f2ea073012935c95171
Pdust:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/Pdust
  hashes:
    binhash: 1e228ce60c923b98e6a6df3f9cae7f5b
    md5: a111e72f65ac3ba178704415f3747ae9
PpoolLeaf:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolLeaf
  hashes:
    binhash: 910a923af99364a1429ea354c98f9763
    md5: 4741f7849ea1f4506434b56e04007c45
PpoolLitterCwd:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolLitterCwd
  hashes:
    binhash: a3441802847f903aae65e03846d6d0cd
    md5: 837bb7fa920609e9588caaca90cac3ae
PpoolLitterMtb:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolLitterMtb
  hashes:
    binhash: 982a92a2bc30be17cdd1742a004ac8cf
    md5: c86bac1aeae5348a82a58f31646535d4
PpoolLitterStr:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolLitterStr
  hashes:
    binhash: 1126a49b95428aab0c86783eaa656f54
    md5: f3e5c969ba0dde02dfee0cdeaec01f68
PpoolRoot:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolRoot
  hashes:
    binhash: e8e77e4396fb900c553128f8616abf12
    md5: e3eddfaad4b303e77e2555038e3f2671
PpoolSoilLabile:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolSoilLabile
  hashes:
    binhash: a1e61d7277f0f434cc48c8cb9dad21f7
    md5: ec3d3bd8a050bf1678c15c4a2219e9d7
PpoolSoilMic:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolSoilMic
  hashes:
    binhash: 95a625d231dca6d65f88d8a9897d6ecc
    md5: 767353d6b2f977e540e607c65fb28665
PpoolSoilOcc:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolSoilOcc
  hashes:
    binhash: e85d2cafdebcb3b21aedaeddd98c1c7a
    md5: dfca33d10800222f6dc8b126346ec8d7
PpoolSoilPass:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolSoilPass
  hashes:
    binhash: 11f088e584aeba0b1d15fd198aaf7329
    md5: 9fd2c9d127b42257bd26faa67dc2d0cd
PpoolSoilSlow:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolSoilSlow
  hashes:
    binhash: 2f3f818235afb0056cf532d5fc725d07
    md5: 631febddb5920a093387f4e8dfe6ac24
PpoolSoilSorb:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolSoilSorb
  hashes:
    binhash: 639a4ba6522d3f6793eb30ec6d8c1141
    md5: b4d66bab1fcbc74944f653e49eb6ba09
PpoolWood:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/PpoolWood
  hashes:
    binhash: 530a490e80020fd658cf5d54a3d7b0a5
    md5: 8909a2c300d57b5b07e2afde1d252ed5
Pweathering:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/Pweathering
  hashes:
    binhash: c97d6586ab5ca858c45044d54b92d4e1
    md5: 9e21214d3bf5fb948c73d2f13d9af764
SoilOrder:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/SoilOrder
  hashes:
    binhash: ad32acea4f703584b867eb0a70069706
    md5: 981387d83cf135188880355a913a4cd7
glai:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/glai
  hashes:
    binhash: dce69ac179994cc032321c8b1589483c
    md5: 160b38c07b05f93ad9f8a3a049538a66
phenphase:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/CASA_ancils_from_ESM15/2025.07.11/phenphase
  hashes:
    binhash: 17d8b2bbb57ac7b8d2bb12c36473ba92
    md5: b146df66179de5744c7535f8225617da
