format: yamanifest
version: 1.0
---
ocean_age.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_age.res.nc
  hashes:
    binhash: 5c7866165163c3ea069cc597bb717b16
    md5: 1e8e455d78bebb3033c79a113cb3655c
ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 0005ef4597434c5464ded1405d6e9d54
    md5: 092be9ef530f779190a0c594fdd3905c
ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 577780e2f9595df37a9fdb656a44b992
    md5: 1ea44fb42e98d4c4d7766a7b6fe69247
ocean_density.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_density.res.nc
  hashes:
    binhash: ad04841724e49ccc3a74a85fc9a98ba7
    md5: 253bb043e1d0806b7eb520741b1276d7
ocean_frazil.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 21f359f46c9d0de8497637d19ce8da5d
    md5: 2b06b2661eeda162fda15752c5920ffc
ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: e1a9252b125a9b6969e5eed507a824ba
    md5: 74b12d6a2f9477f837fb6b41504ea82c
ocean_neutral.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_neutral.res.nc
  hashes:
    binhash: bc2adb140fd5effb5250d385bf678397
    md5: e9b6d2141b08f722857250e9fb85d5ae
ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: f47a1cb8a82c23656d3bb72b2d2af554
    md5: c4a0b4cb65f867f4634f59785a025d3b
ocean_sbc.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 35421bf624b9dc14e18b24d2a52be130
    md5: 9a7ef9ad53f3e675697c4694472e3f1f
ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 461ad5a9af8565c8024d1b6c22ba35e3
    md5: 13cedb1ccde6b993fbd12afc326975f1
ocean_solo.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_solo.res
  hashes:
    binhash: df12f6500d7b176b49fabf6ed7b739e9
    md5: 0a7f2065a637a10105621b9c080a1afd
ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: b7a5c1f53e4a4049275366bfb8a75699
    md5: 8cc18d74a9415dd97ee6c491434067be
ocean_thickness.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 886f49f542c993fb500e20adfcfc92e6
    md5: eb77265831f14ae6800b555d7c21d4bb
ocean_tracer.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_tracer.res
  hashes:
    binhash: 96ef0373a53896376d6d2dd04a124002
    md5: cb8b6540f34aeb7b9db6b306db718e95
ocean_velocity.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 7d4507e5011ac8309fcdc46c57221d9a
    md5: 9bf1bbec82eba4863a017097acc2032e
ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 026b2ade03d347857a72d293625256dd
    md5: 8d3f378cb18c80b6e9ee937ccd328ad2
ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 521467c6442644742ed363219d39bc2a
    md5: bc1c21bbd949508759a916736653e69f
ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/flat10-zec/restart/2026.05.27/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 45c8b8693454432e81cb73ff996d0259
    md5: 1f76d408e4e796b3bba89554b979d329
