format: yamanifest
version: 1.0
---
salt_sfc_restore.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om2/ocean/surface_salt_restoring/global.1deg/2020.05.30/salt_sfc_restore.nc
  hashes:
    binhash: c29c9e14547d5397b069c2aafb0c385e
    md5: b2bd35c44017597ba99b85fb61ed4d72
