format: yamanifest
version: 1.0
---
qrparm.soil_roughness:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/cable_ancils/soil_roughness/prigent12/qrparm.soil_roughness
  hashes:
    binhash: 987f5371756f7424646603e57affcfcd
    md5: 5ee069cea840ddcf55e85e1c3e07e796
qrparm.soil_roughness.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-am3/cable_ancils/soil_roughness/prigent12/qrparm.soil_roughness.nc
  hashes:
    binhash: bf8f44ed7ba86325c59af6192abbedc8
    md5: d89dcded52a9289c1848779a22076eb7
