format: yamanifest
version: 1.0
---
README.md:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/restart/2026.05.29/README.md
  hashes:
    binhash: 570a53154114ffefb6ef66de135fa301
    md5: e678d75a8912d61dc2d04213447abe7c
