format: yamanifest
version: 1.0
---
restart_dump.astart:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/amip/restart/2026.07.21/atmosphere/restart_dump.astart
  hashes:
    binhash: a3cbb3800f6a840718e9871bb0cfe420
    md5: d2e57c1f97a06a06801bc88ba8f3c694
um.res.yaml:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/amip/restart/2026.07.21/atmosphere/um.res.yaml
  hashes:
    binhash: 987cb98d251229848eb0989911e3526a
    md5: 2040b7490b72ee39c2693667166461e3
