format: yamanifest
version: 1.0
---
ocean_hgrid.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.1deg/2020.05.30/ocean_hgrid.nc
  hashes:
    binhash: 3526d89ffb639455c6a1218f5139d5b2
    md5: 51f58be0f4ea6da2cb438a893f95c689
ocean_mosaic.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.1deg/2020.05.30/ocean_mosaic.nc
  hashes:
    binhash: 2eff36650abbdb1e867d8300bf2710cf
    md5: cb42e630ee31d3686156fcbdc2f9d07c
