format: yamanifest
version: 1.0
---
restart_dump.astart:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2026.02.23/atmosphere/restart_dump.astart
  hashes:
    binhash: 67ea68163fb4318926b69da090537057
    md5: e2173eb1b2cd62f49b88dc07a35e361f
um.res.yaml:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial-emissions/restart/2026.02.23/atmosphere/um.res.yaml
  hashes:
    binhash: 0c98e85f8c48299029accab6d8f07b42
    md5: 8befeeca187905b32c0f172ebd997460
