format: yamanifest
version: 1.0
---
LUH2_cable_thinning_frac_1850-2015.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/land/vegetation/global.N96/2024.11.22/LUH2_cable_thinning_frac_1850-2015.nc
  hashes:
    binhash: b28a279fcc343702aaab584e65becdf7
    md5: 1297abbae0e8247a92fab4ab35a6bea3
README.md:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/historical/atmosphere/land/vegetation/global.N96/2024.11.22/README.md
  hashes:
    binhash: a39ecc9b75af362b54c930dd2d08252b
    md5: fe97bdc64c4fd7def5e91a4fecd4499f
