format: yamanifest
version: 1.0
---
ocean_mosaic.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/grids/mosaic/global.25km/2025.09.29/ocean_mosaic.nc
  hashes:
    binhash: 2dcc422a883014541a1bda2027f5973e
    md5: 48ca097393aa50b6980b7a097f7f27b7
