format: yamanifest
version: 1.0
---
ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-om3/mom/initial_conditions/global.25km/2020.10.22/ocean_temp_salt.res.nc
  hashes:
    binhash: 0879960bbd92d63f8c669e74275ff2b4
    md5: 1797b25e6339595a320076080145fd5a
