format: yamanifest
version: 1.0
---
ocean_age.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_age.res.nc
  hashes:
    binhash: 31c9d0ce690ef75ff902111a80b5f870
    md5: 0f919b744609f2ad0f1b5e859de9e5d2
ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 9c82e715b22ecd4306907289b11474f2
    md5: 3d26f300984fdebd9c9ba3d2a8014a2d
ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: afabdc17216ef60699e0a3e22bf6b2f4
    md5: 3e177ef18a1bb3c972c68171ab9de26e
ocean_density.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_density.res.nc
  hashes:
    binhash: eb40af3e07b241c8f7beae0705720079
    md5: 707eb20b21a19b6d72971cda5c5117c1
ocean_frazil.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b10295a82be15d9e7e92dfed94954b04
    md5: 52688ec6d064d3d1d1feca0a4bf4eb74
ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: c16e0bb6e05ca9e54d61ab3ee9f160d1
    md5: cc7ff51207445dd8b7e87e7401dec750
ocean_neutral.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_neutral.res.nc
  hashes:
    binhash: a2b3f957c398b99316de2d9ec56663d2
    md5: bc83bfd59ab020f9bb0563460e3bbebc
ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 24e7611ba675c1188f22d3863626e662
    md5: 4919ba82d6a9786835ba28be4e431c29
ocean_sbc.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 399720955f0120a730a6d3179093fdb8
    md5: 99d707f078a0671de0d2ff8fa018df50
ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 519920d9b55b19932a34991a342cf67d
    md5: 13cedb1ccde6b993fbd12afc326975f1
ocean_solo.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_solo.res
  hashes:
    binhash: 8a64a00537107f5bee7e7fffac1ee1e5
    md5: a5985b5851fbb6e03a745a7d151bc9da
ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 12c4bf335be3b18faad27a9b9dd92997
    md5: 98751a5dd03ebbc41f56f1fff6f1fc05
ocean_thickness.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 23bf60cf0305484f9af1f4af46b1cab2
    md5: a0aade0dc1c5642fdb0035fde8d0ab17
ocean_tracer.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_tracer.res
  hashes:
    binhash: 35b018b6daa4b53aafe9cc45233a4f8e
    md5: e7ea7376dc12775705abff296e73d9b6
ocean_velocity.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 3bf296acf4c1bc0216b7574a419fa49a
    md5: 65cc393bdd15de910f80c3c77ae4e85b
ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4592b1fc540226ce59a22fd197dfa78e
    md5: 78d94efa38a740595984d99c944a96a6
ocean_wombatlite.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: f999fdaa271c4e1f64e4e64b03263c7f
    md5: d9764feee6445b08f82203779830404b
ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p6/modern/pre-industrial/restart/2026.04.07/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: e2fc47c96ea6b22c442f0780d03fda03
    md5: f54fc5bfe1cca3dc027051dff8c6e987
