name: PR
on:
  pull_request: &trigger_config
    branches:
      - main
    paths:
      - .github/manifests/input.yml
  push: *trigger_config
jobs:
  validate-inputs:
    name: Validate
    runs-on: ubuntu-latest
    env:
      INPUT_YAML_PATH: .github/manifests/input.yml
      REQUIRED_FIELDS: description target type cold-storage overwrite inputs
    outputs:
      description: ${{ steps.fields.outputs.description }}
      target: ${{ steps.fields.outputs.target }}
      type: ${{ steps.fields.outputs.type }}
      cold-storage: ${{ steps.fields.outputs.cold_storage }}
      overwrite-target: ${{ steps.fields.outputs.overwrite_target }}
      inputs: ${{ steps.fields.outputs.inputs }}
    steps:
      - uses: actions/checkout@v6

      - name: Read input.yaml fields
        id: fields
        run: |
          echo "description=$(yq '.description' ${{ env.INPUT_YAML_PATH }})" >> $GITHUB_OUTPUT
          echo "target=$(yq '.target' ${{ env.INPUT_YAML_PATH }})" >> $GITHUB_OUTPUT
          echo "type=$(yq '.type' ${{ env.INPUT_YAML_PATH }})" >> $GITHUB_OUTPUT
          echo "cold_storage=$(yq '."cold-storage"' ${{ env.INPUT_YAML_PATH }})" >> $GITHUB_OUTPUT
          echo "overwrite_target=$(yq '.overwrite' ${{ env.INPUT_YAML_PATH }})" >> $GITHUB_OUTPUT
          echo "inputs=$(yq -r '.inputs | to_entries | map("\(.key) \(.value)") | join(",")' ${{ env.INPUT_YAML_PATH }})" >> $GITHUB_OUTPUT

      - name: Validate fields
        if: contains(steps.fields.outputs.*, 'null')
        run: |
          echo "::error::Required fields are missing, check: ${{ env.REQUIRED_FIELDS }}"
          exit 2

  call-remote-copy:
    name: Copy
    needs:
      - validate-inputs
    uses: ./.github/workflows/remote-copy.yml
    with:
      remote: ${{ needs.validate-inputs.outputs.target }}
      type: ${{ needs.validate-inputs.outputs.type }}
      note: ${{ needs.validate-inputs.outputs.description }}
      input: ${{ needs.validate-inputs.outputs.inputs }}
      overwrite-target: ${{ fromJson(needs.validate-inputs.outputs.overwrite-target) }}
      store-on-tape: ${{ fromJson(needs.validate-inputs.outputs.cold-storage) }}
      dry-run: ${{ github.event_name == 'pull_request' }}
    secrets: inherit

  comment-on-pr:
    name: Comment
    needs:
      - validate-inputs
      - call-remote-copy
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # for commenting on the PR with dry-run results
    steps:
      - name: Output Dry Run To PR
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          comment_body=$(cat <<'EOF'
          DRY RUN: Files that would be copied to ${{ needs.validate-inputs.outputs.target }} ${{ needs.validate-inputs.outputs.type }}:

          ```
          ${{ needs.call-remote-copy.outputs.dry-run-copies }}
          ```
          EOF
          )

          gh pr comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --body "$comment_body"
