name: Config Inputs Remote Copy
run-name: "${{ inputs.remote }} ${{ inputs.type }} Config Input Copy"
on:
  workflow_dispatch:
    inputs:
      remote:
        type: choice
        required: true
        description: The HPC that will have it's configurations moved
        options:
          - Gadi
      type:
        type: choice
        required: true
        description: The type of configuration inputs
        options:
          - Release
          - Prerelease
      note:
        type: string
        required: false
        description: Note describing the reason for the change
      input:
        type: string
        required: true
        description: |
          Comma-separated list of 'SOURCE... TARGET' pairs.
          SOURCE is an absolute path to a file/directory accessible to the service user.
          TARGET is a directory relative to the configurations input directory on the HPC for a type.
          Eg. /path/to/copy/access-esm1p5/something access-esm1p5/something/2026.05
      overwrite-target:
        type: boolean
        required: true
        description: Overwrite the remote target if it already exists
      target-acl-spec:
        type: string
        required: false
        # Default to no write for everyone except tm70_ci
        # TODO: This default will probably not work for other `remote-environment`s
        default: >-
          u::rwx,
          u:tm70_ci:rwx,
          g::r-x,
          m::rwx,
          o::---,
          d:u::rwx,
          d:u:tm70_ci:rwx,
          d:g::r-x,
          d:m::rwx,
          d:o::---
        description: ACL spec to be passed to `setfacl -m` for the given target
      store-on-tape:
        type: boolean
        required: true
        default: true
        description: Also store target on the remotes cold storage service
      dry-run:
        type: boolean
        required: false
        default: false
        description: |
          Run the associated commands without actually copying the files
  workflow_call:
    inputs:
      remote:
        type: string
        required: true
        description: The HPC that will have it's configurations moved
      type:
        type: string
        required: true
        description: The type of configuration inputs
      note:
        type: string
        required: false
        description: Note describing the reason for the change
      input:
        type: string
        required: true
        description: |
          Comma-separated list of 'SOURCE... TARGET' pairs.
          SOURCE is an absolute path to a file/directory accessible to the service user.
          TARGET is a directory relative to the configurations input directory on the HPC for a type.
          Eg. /path/to/copy/access-esm1p5/something access-esm1p5/something/2026.05
      overwrite-target:
        type: boolean
        required: true
        description: Overwrite the remote target if it already exists
      target-acl-spec:
        type: string
        required: false
        # Default to no write for everyone except tm70_ci
        # TODO: This default will probably not work for other `remote-environment`s
        default: >-
          u::rwx,
          u:tm70_ci:rwx,
          g::r-x,
          m::rwx,
          o::---,
          d:u::rwx,
          d:u:tm70_ci:rwx,
          d:g::r-x,
          d:m::rwx,
          d:o::---
        description: ACL spec to be passed to `setfacl -m` for the given target
      store-on-tape:
        type: boolean
        required: true
        default: true
        description: Also store target on the remotes cold storage service
      dry-run:
        type: boolean
        required: false
        default: false
        description: |
          Run the associated commands without actually copying the files
    outputs:
      dry-run-copies:
        description: Newline-separated list of files copied in 'SOURCE -> TARGET' format
        value: ${{ jobs.copy-to-remote-dry-run.outputs.copies }}
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      # The `inputs.target-acl-spec` with spaces removed
      formatted-acl: ${{ steps.fmt.outputs.acl }}
    steps:
      - name: Log inputs
        run: |
          echo "::notice::Copy on ${{ inputs.remote }} ${{ inputs.type }}: '${{ inputs.input }}' with ACLs '${{ inputs.target-acl-spec }}'"
          if [[ "${{ inputs.note }}" != "" ]]; then
            echo "::notice::Note from ${{ github.actor }}: '${{ inputs.note }}'"
          fi
          echo "::${{ inputs.overwrite-target && 'warning' || 'notice' }}::This operation ${{ inputs.overwrite-target && 'WILL' || 'will not' }} overwrite the target"

      - name: Verify inputs
        run: |
          errors=false
          pairs='${{ inputs.input }}'
          IFS=,

          for entry in $pairs; do
            entry=$(echo "$entry" | xargs)
            if [[ -z "$entry" ]]; then
              echo "::error::Empty source/target entry found in 'input'."
              errors=true
              continue
            fi

            sources="${entry% *}"
            target_rel="${entry##* }"

            if [[ "$sources" == "$entry" || -z "$sources" || -z "$target_rel" ]]; then
              echo "::error::Invalid source/target entry '$entry'. Expected 'SOURCE TARGET'."
              errors=true
              continue
            fi

            if [[ "$target_rel" = /* ]]; then
              echo "::error::Target '$target_rel' must be relative to the remote configurations input directory."
              errors=true
            fi

            unset IFS

            for source_path in $sources; do
               if [[ "$source_path" != /* ]]; then
                 echo "::error::Source '$source_path' must be an absolute path."
                 errors=true
               fi

              if [[ "$(basename "$source_path")" == "$(basename "$target_rel")" ]]; then
                echo "::error::Entry '$entry' would copy a file into a file or a directory into one with the same name (common rsync error)."
                errors=true
              fi
            done
          done

          if [ -z "${{ inputs.target-acl-spec }}" ]; then
            echo "::notice::No 'ACL' input given, not setting the ACLs explicitly."
          fi

          if [[ "$errors" == "true" ]]; then
            echo "::error::Errors above, exiting..."
            exit 1
          fi

      - name: Format ACL
        id: fmt
        # Remove spaces from ACL string as we have later logic that relies on
        # the IFS=,
        run: |
          acl=$(echo '${{ inputs.target-acl-spec }}' | tr -d ' ')
          echo "Formatted ACL: $acl"
          echo "acl=$acl" >> $GITHUB_OUTPUT

  test-acl:
    name: Test ACL
    runs-on: ubuntu-latest
    if: inputs.target-acl-spec != ''
    needs:
      - setup
    container: rockylinux/rockylinux:8.10
    env:
      TEST_DIR: /opt/test
    steps:
      - name: Create Users in ACL String
        # We don't error out here as it could have been because we are adding the same user twice
        run: |
          set +e
          acl="${{ needs.setup.outputs.formatted-acl }}"
          IFS=,
          for entry in $acl; do
            echo "Testing ACL for u(ser): $entry"
            if [[ $entry =~ ^u(ser)?:([^:]+): ]]; then
              user="${BASH_REMATCH[2]}"
              echo "Adding user $user"
              useradd $user
            fi
          done

      - name: Create Groups in ACL String
        # We don't error out here as it could have been because we are adding the same group twice
        run: |
          set +e
          acl="${{ needs.setup.outputs.formatted-acl }}"
          IFS=,
          for entry in $acl; do
            if [[ $entry =~ ^g(roup)?:([^:]+): ]]; then
              echo "Testing ACL for g(roup): $entry"
              group="${BASH_REMATCH[2]}"
              echo "Adding group $group"
              groupadd $group
            fi
          done

      - name: Verify Valid ACL Spec
        # Now that we have created the users and groups from the ACL string, check if it is valid!
        run: |
          mkdir ${{ env.TEST_DIR }}
          echo "---- Users ----"
          cut -d: -f1 /etc/passwd

          echo "---- Groups ----"
          groups

          if setfacl --test --recursive --modify "${{ needs.setup.outputs.formatted-acl }}" ${{ env.TEST_DIR }}; then
            echo "::notice::ACL Verification Successful. This does not test that the users/groups exist on the remote environment"
          else
            echo "::error::ACL Verification Failed. Check the preceding lines."
            exit 1
          fi

  copy-to-remote-dry-run:
    name: Copy To ${{ inputs.remote }} ${{ inputs.type }} - Dry Run
    if: inputs.dry-run
    runs-on: ubuntu-latest
    needs:
      - setup
      - test-acl
    environment: ${{ inputs.remote }} ${{ inputs.type }}
    outputs:
      copies: ${{ steps.dry-run.outputs.copies }}
    steps:
      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.SSH_HOST }}
            ${{ secrets.SSH_HOST_DATA }}

      - name: Verify Remote Target
        run: |
          pairs='${{ inputs.input }}'
          IFS=,

          for entry in $pairs; do
            entry=$(echo "$entry" | xargs)
            sources="${entry% *}"
            target_rel="${entry##* }"
            target="${{ vars.CONFIGS_INPUT_DIR }}/$target_rel"

            if [[ -z "$sources" || -z "$target_rel" || "$sources" == "$entry" ]]; then
              echo "::error::Invalid source/target entry '$entry'."
              exit 1
            fi
          done

      - name: Rsync Source to Target - Dry Run
        id: dry-run
        env:
          REMOTE_RSYNC_OUTPUTS_FILE: ${{ vars.REMOTE_TMP_DIR }}/remote-copy-dry-run-${{ github.run_id }}-${{ github.run_attempt }}.log
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          pairs='${{ inputs.input }}'
          IFS=,

          echo "::notice::Dry run output below:"

          for entry in $pairs; do
            entry=$(echo "$entry" | xargs)
            sources="${entry% *}"
            target_rel="${entry##* }"
            target="${{ vars.CONFIGS_INPUT_DIR }}/$target_rel"

            # Even in dry-run mode, we need to create intermediate directories so rsync's receiver can chdir into the target!
            mkdir -p "$target"

            rsync_output=$(rsync --dry-run --recursive \
              --out-format="/%f -> $(realpath "$target")/%n" \
              $sources $target
            )

            echo "rsync_output for entry '$entry':"
            echo "$rsync_output"

            echo "$rsync_output" >> ${{ env.REMOTE_RSYNC_OUTPUTS_FILE }}
          done
          EOT

          {
            echo 'copies<<EOF'
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DATA }} -i ${{ steps.ssh.outputs.private-key-path }} \
              cat ${{ env.REMOTE_RSYNC_OUTPUTS_FILE }}
            echo 'EOF'
          } >> $GITHUB_OUTPUT

  copy-to-remote:
    name: Copy To ${{ inputs.remote }} ${{ inputs.type }}
    if: ${{ ! inputs.dry-run }}
    runs-on: ubuntu-latest
    needs:
      - setup
      - test-acl
    environment: ${{ inputs.remote }} ${{ inputs.type }}
    concurrency:
      # We don't want to copy multiple at the same time, especially during the commit step
      group: ${{ inputs.remote }}-${{ inputs.type }}-config-input-copy
      cancel-in-progress: false
      queue: max
    outputs:
      # Space-separated list of paths copied to the target
      files: ${{ steps.copy.outputs.paths }}
      # Space-separated list of manifests created at the target
      manifests: ${{ steps.manifest.outputs.paths }}
    steps:
      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.SSH_HOST }}
            ${{ secrets.SSH_HOST_DATA }}

      - name: Verify Remote Target
        run: |
          pairs='${{ inputs.input }}'
          IFS=,

          for entry in $pairs; do
            entry=$(echo "$entry" | xargs)
            sources="${entry% *}"
            target_rel="${entry##* }"
            target="${{ vars.CONFIGS_INPUT_DIR }}/$target_rel"

            if [[ -z "$sources" || -z "$target_rel" || "$sources" == "$entry" ]]; then
              echo "::error::Invalid source/target entry '$entry'."
              exit 1
            fi
          done

      - name: Rsync Source to Target
        id: copy
        # output:
        #   paths: space-separated list of files copied
        env:
          REMOTE_RSYNC_FILE_LIST_PATH: ${{ vars.REMOTE_TMP_DIR }}/remote-copy-files-${{ github.run_id }}-${{ github.run_attempt }}.log
          LOCAL_RSYNC_FILE_LIST_PATH: ./files-copied.log
        # In this step, we rsync the files from the source to the target, capturing the list of files copied.
        # We keep the remote log as one destination path per line, then make it space-separated for output.
        # There are two rsync steps, one for the rsyncing of source to target,
        # and then one locally on the runner to copy the list of files from the remote.
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          pairs='${{ inputs.input }}'
          IFS=,

          for entry in $pairs; do
            entry=$(echo "$entry" | xargs)
            sources="${entry% *}"
            target_rel="${entry##* }"
            target="${{ vars.CONFIGS_INPUT_DIR }}/$target_rel"

            # Create intermediate directories since we can't use `rsync`s `--mkpath` on some deployment targets
            mkdir -p "$target"

            # The output of the rsync command will be a list of transferred absolute paths, for further processing
            RSYNC_OUT_FORMAT="$(realpath "$target")/%n"

            # Transfer the source to the target, and append destination file paths to the remote log.
            rsync --recursive --out-format="$RSYNC_OUT_FORMAT" \
                ${{ ! inputs.overwrite-target && '--ignore-existing' || '--update' }} \
                $sources $target \
              | grep --invert-match '/$' \
              >> ${{ env.REMOTE_RSYNC_FILE_LIST_PATH }}
          done
          EOT

          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DATA }}:${{ env.REMOTE_RSYNC_FILE_LIST_PATH }} \
            ${{ env.LOCAL_RSYNC_FILE_LIST_PATH }}
          echo "paths=$(tr '\n' ' ' < ${{ env.LOCAL_RSYNC_FILE_LIST_PATH }})" >> $GITHUB_OUTPUT

      - name: Set ACLs on Target
        if: inputs.target-acl-spec != ''
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          declare -A targets
          pairs='${{ inputs.input }}'
          IFS=,

          for entry in $pairs; do
            entry=$(echo "$entry" | xargs)
            target_rel="${entry##* }"
            targets["${{ vars.CONFIGS_INPUT_DIR }}/$target_rel"]=1
          done

          for target in "${!targets[@]}"; do
            setfacl --recursive --modify "${{ needs.setup.outputs.formatted-acl }}" "$target"
            getfacl -t "$target"
          done
          EOT

      - name: Update Manifests
        id: manifest
        # output:
        #   paths: space-separated list of manifests created
        env:
          REMOTE_MANIFEST_FILE_LIST_PATH: ${{ vars.REMOTE_TMP_DIR }}/remote-copy-manifests-${{ github.run_id }}-${{ github.run_attempt }}.log
          LOCAL_MANIFEST_FILE_LIST_PATH: ./manifests-copied.log
          MANIFEST_FILE_NAME: .manifest.yaml
        # Generate manifests for files copied over in the earlier rsync job.
        # Similar to the copy step, we generate a list of manifest paths created on the remote,
        # then copy that to the runner locally so we can set it as output.
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DATA }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          module use ${{ vars.YAMF_MODULE_PATH }}
          module load ${{ vars.YAMF_MODULE_NAME }}

          declare -A manifest_paths
          for path in ${{ steps.copy.outputs.paths }}; do
            echo "Path is $path"
            manifest_dir=$(dirname $path)
            cd $manifest_dir || exit
            manifest_entry_filename=$(basename $path)
            echo "Generating a manifest entry in $manifest_dir for $manifest_entry_filename"

            yamf add -n ${{ env.MANIFEST_FILE_NAME }} --force $manifest_entry_filename
            manifest_paths["$manifest_dir/${{ env.MANIFEST_FILE_NAME }}"]=1
          done
          echo "${!manifest_paths[@]}" > ${{ env.REMOTE_MANIFEST_FILE_LIST_PATH }}
          EOT

          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST_DATA }}:${{ env.REMOTE_MANIFEST_FILE_LIST_PATH }} \
            ${{ env.LOCAL_MANIFEST_FILE_LIST_PATH }}
          echo "paths=$(cat ${{ env.LOCAL_MANIFEST_FILE_LIST_PATH }})" >> $GITHUB_OUTPUT

      - name: Commit Updated Manifests to ${{ github.repository }}
        # TODO: For future remote-environments, we would have to alter the structure of model-config-inputs to be demarcated by target at the root level. For now, only allow Gadi to commit.
        if: inputs.type == 'Release'
        env:
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          eval $(gpg-agent --daemon)
          $(gpgconf --list-dirs libexecdir)/gpg-preset-passphrase \
            --passphrase '${{ secrets.GH_ACTIONS_BOT_GPG_PASSPHRASE }}' \
            --preset '${{ secrets.GH_ACTIONS_BOT_GPG_KEYGRIP }}'

          if ! cd "${{ vars.CONFIGS_INPUT_DIR }}"; then
            echo "::error::Can't CD into vars.CONFIGS_INPUT_DIR to commit"
            exit 2
          fi

          git add .
          git commit -m "Updated manifests and READMEs as part of ${{ env.RUN_URL }}"
          git push
          EOT

  copy-to-tape-gadi:
    name: Copy To Tape On ${{ inputs.remote }} ${{ inputs.type }}
    runs-on: ubuntu-latest
    needs:
      - copy-to-remote
    if: inputs.store-on-tape && inputs.remote == 'Gadi'
    environment: ${{ inputs.remote }} ${{ inputs.type }}
    concurrency:
      # We don't want to copy multiple at the same time
      group: ${{ inputs.remote }}-${{ inputs.type }}-config-input-tape-copy
      cancel-in-progress: false
      queue: max
    steps:
      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.SSH_HOST }}
            ${{ secrets.SSH_HOST_DATA }}

      - name: Send Target to Tape
        # For each of the absolute paths of copied files and manifests, put
        # the file (and it's directories relative to inputs.target) on the tape storage
        # under a datestamp directory.
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          now=$(date +%Y_%m_%d_%H_%M)

          for file in ${{ needs.copy-to-remote.outputs.files }} ${{ needs.copy-to-remote.outputs.manifests }}; do
            file_relative_to_config_dir=${file#${{ vars.CONFIGS_INPUT_DIR }}/}
            echo "Moving '$file' to '${{ vars.TAPE_ROOT_DIR }}/${{ vars.ENVIRONMENT_TYPE }}/$now/$file_relative_to_config_dir'"

            # Create all intermediate directories before putting the file
            intermediate_dirs=$(dirname $file_relative_to_config_dir)
            mdss -P ${{ vars.PROJECT_CODE }} mkdir -p ${{ vars.TAPE_ROOT_DIR }}/${{ vars.ENVIRONMENT_TYPE }}/$now/$intermediate_dirs

            # Copy the file itself to tape
            mdss -P ${{ vars.PROJECT_CODE }} put $file ${{ vars.TAPE_ROOT_DIR }}/${{ vars.ENVIRONMENT_TYPE }}/$now/$file_relative_to_config_dir
          done

          echo "Output:"
          mdss -P ${{ vars.PROJECT_CODE }} ls -R ${{ vars.TAPE_ROOT_DIR }}/${{ vars.ENVIRONMENT_TYPE }}/$now
          EOT
